{{- if .Values.groundStation.ingress.enabled -}}
{{- include "private-assistant.ingress" (dict "component" "ground-station" "serviceName" "ground-station" "nameSuffix" "" "config" .Values.groundStation.ingress "context" .) }}
{{- end }}
