{{- $clusterDomain := .Values.clusterDomain | default "" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-assistant.fullname" . }}-ground-station-config
  labels:
    {{- include "private-assistant.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ include "private-assistant.groundStationConfig" . | nindent 4 }}
    {{- .Values.groundStation.config | nindent 4 }}
