{{- if and .Values.webUi.enabled .Values.webUi.frontend.ingress.enabled -}}
{{- include "private-assistant.ingress" (dict "component" "webui-frontend" "serviceName" "webui-frontend" "nameSuffix" "webui-frontend" "config" .Values.webUi.frontend.ingress "context" .) }}
{{- end }}
