{{- if and .Values.webUi.enabled .Values.webUi.backend.ingress.enabled -}}
{{- include "private-assistant.ingress" (dict "component" "webui-backend" "serviceName" "webui-backend" "nameSuffix" "" "config" .Values.webUi.backend.ingress "context" .) }}
{{- end }}
